#!/bin/bash

set -u
set -e

run_ressh() {
  source "$HOME/.aliases"
  ressh
}

commit_and_push() {
  set +e
  g add .
  echo -e "Committing and pushing new gh-pages...\n"
  git commit -m "Add version $npm_package_version"
  run_ressh
  git push origin gh-pages
  set -e
}

#TEMP_DIRECTORY=/tmp/braintree-web-drop-in-temp
BT_DROPIN_DIR=~/bt/braintree-web-drop-in

#if [ -d "$TEMP_DIRECTORY" ]; then
#  rm -rf "$TEMP_DIRECTORY"
#fi

echo -e "Building jsdoc...\n"
cd "$BT_DROPIN_DIR" && npm run build:gh-pages
#cp -r $BT_DROPIN_DIR/dist/gh-pages $TEMP_DIRECTORY

echo -e "Building dropin...\n"
npm run build

git checkout gh-pages
git pull

git config user.name Braintree
git config user.email code@getbraintree.com

echo -e "Copying new jsdocs gh-pages...\n"
cp -r dist/gh-pages/* .

echo -e "Copying new dropin.css/js...\n"
cp dist/web/dropin/dev/css/dropin.css web/dropin/dev/css
cp dist/web/dropin/dev/js/dropin.js web/dropin/dev/js

#cp -r $TEMP_DIRECTORY/docs/$npm_package_version .
#cp -r $TEMP_DIRECTORY/docs/current .
#cp -r $TEMP_DIRECTORY/index.html .

commit_and_push

#echo -e "Removing cloned braintree-web"
#rm -rf "$TEMP_DIRECTORY"

echo -e "Checking out previous branch...\n"
git checkout -

echo "Finished, exiting."
